namespace: ansible
name: posix
version: 0.1.1
readme: README.md
authors:
  - Ansible (github.com/ansible)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: [posix, networking, shell, unix]
dependencies: {}
repository: https://github.com/ansible-collections/ansible.posix
documentation: https://github.com/ansible-collections/ansible.posix/tree/master/docs
homepage: https://github.com/ansible-collections/ansible.posix
issues: https://github.com/ansible-collections/ansible.posix
